pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image 'nginx:latest' }
      }
      steps {
        echo "Running NGINX version check........."
        sh 'nginx -v'
      }
    }
    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        sh 'node --version'
      }
    }
  }
}
